### ISSUE TITLE
Dependency installation with npm fails

### ISSUE THREAD

**Issue by malaakso** [CreatorDev/ci40-kiwano-webapp#2]
Installing creator-js-client fails since the line
`"creator-js-client": "https://github.com/CreatorDev/creator-js-client.git",`
in package.json is invalid. It should be
`"creator-js-client": "git://github.com/CreatorDev/creator-js-client.git",`
instead.

**Comment by payalsarnot** [comment]
@malaakso tried 'npm install' and it works fine with me. Can you please let us know your 'npm --version'?

**Comment by malaakso** [comment]
@payalsarnot it's 1.3.10 (which is old, I know). According to [this](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), plain https is not correct.

**Comment by payalsarnot** [comment]
@malaakso what I see from logs is 
"+-- creator-js-client@2.0.0  (git+https://github.com/CreatorDev/creator-js-client.git#a058bf7e06b391b8502ee1c2775c929181dae79c)"

**Comment by ghost** [comment]
Hi @malaakso,

We've updated the creator-js-client dependency URL: https://github.com/CreatorDev/ci40-kiwano-webapp/commit/a4b9288f96fd29c4281327212e90633f08160118

Thank you for your suggestion.

Best regards,
Hugo
